config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/speakers' => 'users#speakers'

  resources :users
  resources :sessions
  resources :howitworks
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user


  #Add image for event
  has_attached_file :photo, :styles => { :small => "150x150>" }, :url  => "/assets/products/:id/:style/:basename.:extension", :default_url => "/assets/products/5/original/event-default.jpeg?1415837387"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events

  #Add profile photo for user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit # and 'update', and 'destroy'
    if !can_edit?
      render_forbidden
    end
      # render_forbidden and return unless can_edit?
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if can_edit? == true
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render_forbidden
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def can_edit?
      @event = Event.find(params[:id])
      if current_user && current_user.events.include?(@event)
        return true
      else
        return false
      end
    end

    def render_forbidden
      redirect_to events_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :date, :tagline, :website, :topics, :description, :photo)
    end
end

app/controllers/howitworks_controller.rb
class HowitworksController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create, :speakers]

  def index
    @users = User.all
  end

  def new
    @user = User.new

  end

  def speakers
    @users = User.all
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :location,
      :bio,
      :tagline,
      :fee_range,
      :willing_to_speak_for_free,
      :website,
      :avatar
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Signin Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security Checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end
end

app/views/common/_signout.html.erb
<% if signed_in? %>

  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    <%= link_to "My Profile", current_user, class: "btn btn-default", id: "sm-homebutton" %>
    <%= f.submit "Sign out", id: 'signout', class: "btn btn-default", id: "sm-homebutton" %>
  <% end %>

  <!-- <%= link_to "Home", root_path %> -->

<% else %>

  <%= link_to "Sign In", signin_path, class: "btn btn-default", id: "sm-homebutton" %> <%= link_to "Sign up", signup_path, class: "btn btn-default", id: "sm-homebutton" %>

<% end %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
<b>Errors:</b>
<ul>
  <% @event.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>



<%= form_for @event, :html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :topics %><br>
    <%= f.text_field :topics %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container">
  <h1>Events</h1>
  <div class="col-sm-4">
    Search Section
  </div>
  <div class="col-sm-8">
    Events
    <% @events.each do |event| %>
      <div class="row event-blob">
        <%= image_tag event.photo.url, class: "event-pic" %>
        <ul>
          <li class="name"><a href="/events/<%= event.id %>"><%= event.name %></li></a>
          <li class="city"><%= event.location %></li>
          <li>Tagline: <%= event.tagline %></li>
          <li>Topics: <%= event.topics %></li>
          <li>Description: <%= event.description %></li>
          <li class="date"><%= event.date %></li>
          <li><%= event.website %></li>
        </ul>
      </div><hr>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @event.tagline %>
</p>

<p>
  <strong>Website:</strong>
  <%= @event.website %>
</p>

<p>
  <strong>Topics:</strong>
  <%= @event.topics %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <%= image_tag @event.photo.url %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/howitworks/index.html.erb
<div class="container">
  
  <div class="row"></div>
  
  <h1 class="heading">How It Works</h1>
  <img src="/assets/mic.png" class="mic">
  <div class="hiw">
    <p>Welcome to Orate, the ultimate app for connecting speakers with event hosts. This convenient app systematizes and streamlines what is otherwise a haphazard communication process. The website allows visitors to view speakers and events that have already been posted, and facilitates sign in/login for those who want to be listed as speakers or event hosts themselves.</p>
    <p>Once you have created a user account and profile, you can list attributes such as your name, contact info, and a bio for speakers or an event description for event hosts that is then viewable to the public. Orate also enables users to search for events and speakers by their own search terms.</p>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Enable Bootstrap to be mobile friendly -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Orate</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
          </li>
          <li class="active"><a href="/howitworks">How It Works</a></li>
          <li class="active">
            <form class="navbar-form navbar-left">
              <div class="form-group">
                <a href="/speakers" class="btn btn-default">Find a Speaker</a>
                <a href="/events" class="btn btn-default">Find an Event</a>
              </div>
            </form>
          </li>
        </ul>

        <div class="navbar-form navbar-right">
          <%= render 'common/signout' %>
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

<div class="footer">
  <div class="container">
    <p>About Us, Terms of Service, Privacy Policy</p>
  </div>
</div>


</body>

</html>

app/views/users/_fulluser_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user, :html => { :multipart => true } do |f| %>
  <%= f.text_field :name, placeholder: 'name', class: 'field' %>

  <%= f.email_field :email, placeholder: 'email', class: 'field' %>

  <%= f.password_field :password, placeholder: 'password', class: 'field' %>

  <%= f.password_field :password_confirmation, placeholder: 'confirm password', class: 'field' %>

  <%= f.text_field :tagline, placeholder: 'tagline', class: 'field' %>


  <%= f.text_field :location, placeholder: 'location', class: 'field' %>
  
  <%= f.number_field :fee_range, in: 0..10000.0, step: 10, placeholder: 'minimum fee (in USD)', class: 'field' %>

  <%= f.url_field :website, placeholder: 'website', class: 'field' %>

  <div class="col-md-8"><%= f.text_area :bio, placeholder: 'bio', class: 'field', id: 'bio' %></div>
  
  <div id="choose-file"><%= f.file_field :avatar, class: 'photo-field' %></div>

  <%= f.submit "Submit", id: 'submit' %>
<% end %>

app/views/users/_user_form.html.erb
  <% if @user.errors.any? %>
  <b>Errors:</b>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_for @user do |f| %>
    <div><%= f.text_field :name, placeholder: 'name', class: 'field' %></div>

    <div><%= f.text_field :email, placeholder: 'email', class: 'field' %></div>

    <div><%= f.password_field :password, placeholder: 'password', class: 'field'  %></div>

    <div><%= f.password_field :password_confirmation, placeholder: 'confirm password', class: 'field'  %></div>

    <%= f.submit "Submit", id: 'submit' %>
  <% end %>

app/views/users/edit.html.erb
<div class="container row form">
  
  <h1 class="col-lg-12 col-sm-12 col-md-12" id="page-title">Edit <%= @user.name.capitalize %>'s Profile</h1>
  <div class="col-xs-8 col-sm-8 col-md-10" id="form_2">
    <%= image_tag @user.avatar.url, class: "profile-pic" %>
    <%= render "fulluser_form" %>

    <hr>

    <%= form_for @user, method: 'delete' do |f| %>
        <p id="page-text">Delete your account?</p> <%= f.submit "Delete", class: "btn btn-default", id: 'page-button-one' %>
        <%= link_to "Cancel", @user, class: "btn btn-default", id: 'page-button-one' %>
    <% end %>

  </div>

</div>

app/views/users/index.html.erb
<div class="container">

  <h1>User Index</h1>

    <% @users.each do |user| %>
      <p><%= user.name %></p>
    <% end %>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row form">
    <h1 class="col-lg-12 col-sm-12 col-md-12">Create a User</h1>
    <div class="col-xs-2 col-sm-2 col-md-2" id="form_2"><%= render "user_form" %></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-sm-4">
    <div><%= image_tag @user.avatar.url, class: "profile-pic" %></div>
    <p class="field2"><%= @user.location %></p>
    <p class="field2"><%= @user.fee_range %></p>
    <p class="field2"><%= @user.website %></p>
  </div>
  <div class="col-sm-8">
    <h1><%= @user.name.capitalize %></h1>
    <p><%= @user.tagline %></p>
    <p><%= @user.bio %></p>

  </div>

  <button class="btn btn-default" id="edit_btn"><%= link_to "Edit", edit_user_path(@user) %></button>

</div>

app/views/users/speakers.html.erb
<div class="container">
  <h1>Speakers</h1>
  <div class="col-sm-4">
    Search Section Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
  <div class="col-sm-8">
    <% @users.each do |user| %>
    <div class="profiles-wrapper">
      <a class="profile-card-link" href="/users/<%= user.id %>">
      <div class="profile-card">
        <%= image_tag user.avatar.url, class: "profile-card-pic" %>
        <div class="profile-card-wrapper">
          <div class="profile-current-location">
            <%= user.location %>
          </div>
          <ul>
            <li><h2><%= user.name %></h2></li>
            <li><h3><%= user.tagline %></h3></li>
            <li><%= user.bio %></li>
            <li><%= user.fee_range %></li>
            <li><%= user.website %></li>
          </ul>
        </div>
      </div>
      </a>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<!-- BACKGROUND VIDEO -->
<video autoplay loop muted id="bgvid">
<source src="<%= image_path("watch.mp4") %>" type="video/mp4">
  Your browser does not support the video tag.
</video>

<!-- TITLE AND COPY VIDEO OVERLAY -->
<section class="content-section video-section">
  <div class="pattern-overlay">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h2 id="landing-tagline">connecting speakers to events</h2>
          <div class="form-group" id="landing-buttons">
            <a href="/signup" class="btn btn-default">Create a Profile</a>
            <a href="/events/new" class="btn btn-default">Submit an Event</a>
            <a href="/howitworks" class="btn btn-default">How It Works</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="placeholder-section">
  <div class="container">
    <div class="col-md-6">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
    <div class="col-md-6">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
  </div>
</section>